name: Netlify Deploy URLs of changed pages

on:
  pull_request:
  
jobs:
  debug:
    name: URLs
    runs-on: ubuntu-latest
 
    steps:
    - name: Get list of changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: List Netlify Deploy URLs
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          if [[ $changed_file == content/* ]]
          then
            cleaned_file=$(echo "$changed_file" | sed -e 's/[0-9]//g' | sed -e 's/.mdx//g' | sed -e 's/\/-/\//g' | sed -e 's/content\///g')
            # TODO special case for index.mdx
            # TODO special case for images and similar non .mdx files
            echo "- https://deploy-preview-${{github.event.number}}--prisma2-docs.netlify.app/docs/$cleaned_file"
          fi   
        done
    - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: demo cleaned_file link
        conclusion: neutral
        details_url: https://deploy-preview-${{github.event.number}}--prisma2-docs.netlify.app/docs/$cleaned_file

