name: Netlify Deploy URLs of changed pages

on:
  pull_request:
  
jobs:
  debug:
    name: URLs
    runs-on: ubuntu-latest
 
    steps:
    - name: Get list of changes files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: List URLs
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          if [[ $changed_file == content/* ]]
          then
            echo "Do something with this ${changed_file}."
            echo "https://deploy-preview-${{ github.context.payload.number }}--prisma2-docs.netlify.app/docs/"
          fi   
        done
