name: Netlify Deploy URLs of changed pages

on:
  pull_request:
  
jobs:
  debug:
    name: URLs
    runs-on: ubuntu-latest
 
    steps:
    - name: Get list of changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: List Netlify Deploy URLs
      id: links
      run: |
        body="This PR changes the following pages (Netlify Preview Deploy links):\n\n"
        for changed_file in ${{ steps.files.outputs.all }}; do
          if [[ $changed_file == content/* ]]
          then
            cleaned_file=$(echo "$changed_file" | sed -e 's/[0-9]//g' | sed -e 's/.mdx//g' | sed -e 's/\/-/\//g' | sed -e 's/content\///g')
            # TODO special case for index.mdx
            # TODO special case for images and similar non .mdx files
            echo "- https://deploy-preview-${{github.event.number}}--prisma2-docs.netlify.app/docs/$cleaned_file"

            link="\n- [$cleaned_file](https://deploy-preview-${{github.event.number}}--prisma2-docs.netlify.app/docs/$cleaned_file)""
            body="$body$link"
          fi   
        done
        echo "ßßßß"
        echo body
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0D'}"
        echo "????"
        echo body
        echo "::set-output name=body::$body"

    # - uses: LouisBrunner/checks-action@v1.1.1
    #   if: always()
    #   with:
    #     token: ${{ secrets.PERSONAL_GITHUB_TOKEN_FOR_GH_ACTIONS }}
    #     name: demo cleaned_file link
    #     conclusion: success
    #     details_url: https://deploy-preview-${{github.event.number}}--prisma2-docs.netlify.app/docs/$cleaned_file
    #     action_url: https://deploy-preview-${{github.event.number}}--prisma2-docs.netlify.app/docs/$cleaned_file
    # Blocked by https://github.com/LouisBrunner/checks-action/issues/18
    - name: Find existing comment
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: following pages

    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.links.outputs.body }}

    - name: Update comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: ${{ steps.links.outputs.body }}
        edit-mode: replace

